import { normalizePackagePath } from "./local-review-package.ts";

export type ReviewRegistryEntry = {
  slug: string;
  title: string;
  base_path: string;
};

export type ReviewRegistry = {
  schema_version: 1;
  default_review: string;
  reviews: ReviewRegistryEntry[];
};

const REGISTRY_KEYS = new Set(["schema_version", "default_review", "reviews"]);
const ENTRY_KEYS = new Set(["slug", "title", "base_path"]);
const REVIEW_SLUG = /^[a-z0-9][a-z0-9-]{0,79}$/;
const MAX_REVIEWS = 100;
const MAX_TITLE_CHARS = 160;

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === "object" && !Array.isArray(value);
}

function hasExactKeys(value: Record<string, unknown>, keys: Set<string>) {
  return Object.keys(value).length === keys.size && Object.keys(value).every((key) => keys.has(key));
}

/**
 * Validate the same-origin registry generated by the publish step.
 *
 * Restricting each base path to its canonical slug prevents a malformed
 * registry from turning the viewer's artifact fetches into arbitrary URL
 * requests. Review contents remain completely generic below that boundary.
 */
export function validateReviewRegistry(value: unknown): ReviewRegistry {
  if (!isRecord(value) || !hasExactKeys(value, REGISTRY_KEYS) || value.schema_version !== 1) {
    throw new Error("Review registry has an unsupported structure or schema version");
  }
  if (!Array.isArray(value.reviews) || !value.reviews.length || value.reviews.length > MAX_REVIEWS) {
    throw new Error(`Review registry must declare 1 through ${MAX_REVIEWS} reviews`);
  }
  const slugs = new Set<string>();
  const basePaths = new Set<string>();
  const reviews = value.reviews.map((raw, index) => {
    if (!isRecord(raw) || !hasExactKeys(raw, ENTRY_KEYS)) {
      throw new Error(`Review registry entry ${index + 1} has an unsupported structure`);
    }
    if (typeof raw.slug !== "string" || !REVIEW_SLUG.test(raw.slug) || slugs.has(raw.slug)) {
      throw new Error(`Review registry entry ${index + 1} has an invalid or duplicate slug`);
    }
    try {
      normalizePackagePath(raw.slug);
    } catch {
      throw new Error(`Review registry entry ${index + 1} has a nonportable slug`);
    }
    if (
      typeof raw.title !== "string" || !raw.title.trim() || raw.title !== raw.title.trim()
      || raw.title.length > MAX_TITLE_CHARS || /[\r\n\u0000-\u001f\u007f]/.test(raw.title)
    ) {
      throw new Error(`Review registry entry ${index + 1} has an invalid title`);
    }
    const expectedBasePath = `/reviews/${raw.slug}`;
    if (raw.base_path !== expectedBasePath || basePaths.has(raw.base_path)) {
      throw new Error(`Review registry entry ${index + 1} has an invalid or duplicate base path`);
    }
    slugs.add(raw.slug);
    basePaths.add(raw.base_path);
    return { slug: raw.slug, title: raw.title, base_path: raw.base_path };
  });
  if (typeof value.default_review !== "string" || !slugs.has(value.default_review)) {
    throw new Error("Review registry default_review must name a declared review");
  }
  return { schema_version: 1, default_review: value.default_review, reviews };
}
