"""首轮 GitHub 调研的规范候选数据。仅供生成知识库和交付物。"""

AS_OF = "2026-08-06"

CATEGORIES = {
    "01": "学术写作、引用与出版",
    "02": "文档、表格、演示文稿与办公自动化",
    "03": "文献检索与学术研究",
}

REPOSITORIES = {
    "K-Dense-AI/scientific-agent-skills": {"stars": 32811, "pushed": "2026-08-03", "license": "MIT", "branch": "main"},
    "ShaishavMaisuria/research-paper-lifecycle-skills": {"stars": 21, "pushed": "2026-06-27", "license": "Apache-2.0", "branch": "main"},
    "zLanqing/codex-claude-academic-skills": {"stars": 2613, "pushed": "2026-05-14", "license": "MIT", "branch": "main"},
    "beita6969/ScienceClaw": {"stars": 872, "pushed": "2026-06-08", "license": "MIT", "branch": "main"},
    "wentorai/research-plugins": {"stars": 270, "pushed": "2026-06-19", "license": "MIT", "branch": "main"},
    "stephenturner/skill-peer-review-assistant": {"stars": 33, "pushed": "2026-06-30", "license": "MIT", "branch": "main"},
    "WUBING2023/PaperSpine": {"stars": 4663, "pushed": "2026-07-28", "license": "MIT", "branch": "main"},
    "anthropics/skills": {"stars": 166590, "pushed": "2026-07-24", "license": "各技能目录独立许可证", "branch": "main"},
    "openai/skills": {"stars": 24564, "pushed": "2026-07-14", "license": "各技能目录独立许可证", "branch": "main"},
    "claude-office-skills/skills": {"stars": 362, "pushed": "2026-01-31", "license": "MIT", "branch": "main"},
    "EvotecIT/OfficeIMO": {"stars": 499, "pushed": "2026-08-06", "license": "MIT", "branch": "master"},
    "Leo1998-Lu/ai-paper2slide-skill": {"stars": 95, "pushed": "2026-07-08", "license": "MIT", "branch": "main"},
    "bowenliang123/markdown-exporter": {"stars": 258, "pushed": "2026-07-16", "license": "Apache-2.0", "branch": "main"},
    "dachent/skills": {"stars": 18, "pushed": "2026-08-03", "license": "MIT", "branch": "main"},
    "kangminlee-maker/excel-workbook-editing": {"stars": 0, "pushed": "2026-06-29", "license": "MIT", "branch": "main"},
    "Community-Access/accessibility-agents": {"stars": 382, "pushed": "2026-08-04", "license": "MIT", "branch": "main"},
    "ustc-ai4science/academic-search": {"stars": 532, "pushed": "2026-07-05", "license": "MIT", "branch": "main"},
    "jkitchin/litdb": {"stars": 83, "pushed": "2026-04-07", "license": "MIT", "branch": "main"},
    "wentorai/Research-Claw": {"stars": 849, "pushed": "2026-08-01", "license": "未明确", "branch": "main"},
    "keemanxp/slr-prisma": {"stars": 90, "pushed": "2026-03-28", "license": "未明确", "branch": "main"},
}


def c(cid, name, cn, cat, repo, path, ecosystem, form, tags, summary, detail,
      roles, scenario, compat, adapt, deps, risk, verify, priority, related=""):
    return {
        "id": cid, "name": name, "cn": cn, "cat": cat, "repo": repo,
        "path": path, "ecosystem": ecosystem, "form": form, "tags": tags,
        "summary": summary, "detail": detail, "roles": roles,
        "scenario": scenario, "compat": compat, "adapt": adapt,
        "deps": deps, "risk": risk, "verify": verify,
        "priority": priority, "related": related,
    }


CANDIDATES = [
    c("GH-01-0001", "scientific-writing", "科学论文写作与审计", "01", "K-Dense-AI/scientific-agent-skills", "skills/scientific-writing/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "科学写作、证据溯源、报告规范、投稿准备", "起草、修订并审计科学论文或研究报告。", "用证据清单、声明记录和一致性检查把写作、事实核验与最终批准分开；附带本地脚本、模板和报告规范。", "学生、科研人员、教学人员", "论文各章节写作、报告规范核对、投稿前一致性审查", "A", "可直接按 Codex skill 方式使用；按学科补充本校模板。", "Python 3.11+ 仅用于可选本地脚本", "不应把生成文本视为证据；未发表材料需按授权边界处理。", "二级包内容验证", "高"),
    c("GH-01-0002", "citation-management", "引文与 BibTeX 管理", "01", "K-Dense-AI/scientific-agent-skills", "skills/citation-management/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "引文检索、DOI、BibTeX、参考文献核验", "检索论文元数据、验证引文并生成规范 BibTeX。", "覆盖 OpenAlex、PubMed、Google Scholar 等发现路径，提供 DOI 元数据核验、重复检查和多种引文格式流程。", "学生、科研人员、图书馆人员", "毕业论文参考文献、课题组文献库、投稿前引文核对", "A", "直接使用流程；外部检索工具按可用性替换。", "学术数据库或搜索工具；部分流程需要网络", "数据库覆盖和速率不同；自动格式化仍需抽查。", "二级包内容验证", "高"),
    c("GH-01-0003", "venue-templates", "期刊与会议模板适配", "01", "K-Dense-AI/scientific-agent-skills", "skills/venue-templates/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "期刊模板、会议格式、匿名规则、页面限制", "按目标期刊或会议选择并核对稿件、海报和基金文档模板。", "强调实时核验官方模板与页数、匿名和补充材料规则，并提供 LaTeX 脚手架与提交 PDF 检查流程。", "科研人员、研究生", "会议投稿、期刊改投、匿名稿与终稿格式检查", "A", "直接采用验证优先流程；为本校常投期刊建立本地配置。", "LaTeX/PDF 工具；需要访问当前官方作者指南", "投稿规则会变化，缓存模板不能代替实时核对。", "说明已核验", "高"),
    c("GH-01-0004", "pyzotero", "Zotero 程序化管理", "01", "K-Dense-AI/scientific-agent-skills", "skills/pyzotero/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "Zotero、文献库、标签、附件、API", "通过 pyzotero 操作 Zotero 文献库、集合、标签和附件。", "面向 Zotero Web API v3，提供查询、创建、更新、导出和附件管理示例，适合构建课题组文献自动化。", "科研人员、学生、图书馆人员", "共享文献库维护、参考文献批量导出、标签整理", "B", "配置 Zotero API 凭据并限制写操作；先以只读查询接入。", "pyzotero、Zotero Web API、用户或群组密钥", "写入和删除会改变文献库；凭据与附件权限需单独管理。", "说明已核验", "中"),
    c("GH-01-0005", "orchestrate-paper", "论文全生命周期编排", "01", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/orchestrate-paper/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "论文流程、阶段门、投稿编排、验证", "从研究想法到投稿组织论文生命周期技能。", "以目标—计划—执行—验证—反思循环调用文献、写作、预检和模拟评审等兄弟技能，并在阶段门要求作者确认。", "科研人员、研究生", "课题论文进度管理、投稿路线规划、团队检查点", "B", "需要同时引入其兄弟技能或改写路由表。", "同仓库多个生命周期 skill；部分阶段需要实时网页信息", "不能替代作者决策，也不应自动投稿。", "二级包内容验证", "高"),
    c("GH-01-0006", "draft-related-work", "相关工作章节写作", "01", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/draft-related-work/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "相关工作、主题聚类、研究差异、引文覆盖", "基于实际检索论文起草或重写 Related Work。", "从论文主张推导应覆盖的研究簇，逐簇说明差异并设置引文下限；空缺主题会返回检索流程。", "科研人员、研究生", "论文相关工作重构、补齐研究脉络和差异定位", "B", "与检索和引文验证技能配套；替换目标学科的章节惯例。", "find-papers 或现有 BibTeX 文献库", "检索不足会导致主题失衡；不应生成未核验引文。", "说明已核验", "高"),
    c("GH-01-0007", "verify-citations", "参考文献真实性核验", "01", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/verify-citations/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "BibTeX、Crossref、DBLP、Semantic Scholar、arXiv", "逐条验证 BibTeX 文献并发现虚构、错误和重复条目。", "交叉使用多个学术来源检查 DOI、作者、年份、期刊会议、重复和撤稿信号，并输出修正入口。", "科研人员、研究生、编辑支持人员", "毕业论文与投稿稿件参考文献审计", "B", "映射到 Codex 可用的检索工具；保留人工打开原始记录步骤。", "外部学术 API；仓库脚本", "API 未解析不等于论文不存在，撤稿状态需人工复核。", "说明已核验", "高"),
    c("GH-01-0008", "write-abstract", "摘要与关键词撰写", "01", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/write-abstract/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "摘要、关键词、字数限制、摘要注册", "按投稿场景撰写、缩写和检查论文摘要。", "使用动机—空白—方法—结果—影响结构，处理关键词体系、字符预算和提前摘要注册材料。", "科研人员、研究生", "会议摘要注册、期刊摘要改写、学位论文摘要", "B", "将会场规则核验接口替换为当前可用网页工具。", "目标会场当前指南；可选检查脚本", "摘要不能补造尚未确认的结果；字数规则会变化。", "说明已核验", "高"),
    c("GH-01-0009", "plan-submission", "投稿倒排计划", "01", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/plan-submission/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "投稿计划、截止日期、系统账户、材料清单", "从会议或期刊截止日期反推投稿准备计划。", "涵盖摘要注册、作者冻结、系统账户、补充材料、双重投稿检查以及评审和终稿阶段。", "科研人员、研究生、科研管理人员", "会议投稿排期、课题组多人协作、终稿准备", "B", "接入日历前先保持只读计划；规则从官方 CFP 核验。", "实时 CFP 或作者指南", "截止日期、时区和系统规则需实时核对。", "说明已核验", "中"),
    c("GH-01-0010", "prepare-camera-ready", "终稿与出版前准备", "01", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/prepare-camera-ready/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "camera-ready、版权、ORCID、PDF 检查、去匿名", "为录用论文生成可执行的终稿准备清单并检查常见错误。", "覆盖 ACM、IEEE、OpenReview 等不同出版轨道中的版权、元数据、PDF 检查、文件命名、去匿名和页数规则。", "科研人员、研究生", "录用后终稿、版权材料和出版系统准备", "B", "保留咨询和本地 lint，禁止自动提交表单。", "LaTeX/PDF 工具；目标出版轨道信息", "出版规则与表单具有时效性；最终提交必须人工完成。", "说明已核验", "高"),
    c("GH-01-0011", "work-with-overleaf", "Overleaf 协作桥接", "01", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/work-with-overleaf/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "Overleaf、LaTeX、同步、Git、ZIP", "把 Overleaf 项目接入本地论文检查和修改流程。", "支持 Overleaf Git、GitHub 同步和 ZIP 三种路径，强调先拉取、差异检查、凭据保密和推送确认。", "科研人员、研究生", "课题组 Overleaf 稿件本地预检、同步修改", "B", "根据账号权限选择同步路径；所有回写都要求单独确认。", "Overleaf 账号；可选 Git 权限或 ZIP", "令牌与未发表稿件敏感；错误同步可能覆盖协作内容。", "说明已核验", "中"),
    c("GH-01-0012", "write-rebuttal", "审稿意见回复与 rebuttal", "01", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/write-rebuttal/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "rebuttal、作者回复、字符预算、修订说明", "按会场格式起草逐点审稿回复和 rebuttal。", "支持一页 LaTeX、OpenReview 字符预算和期刊 revise-and-resubmit 三类轨道，并将回复锚定到正文位置。", "科研人员、研究生", "会议 rebuttal、期刊修回说明、审稿意见覆盖检查", "B", "替换会场配置并保留作者逐条批准。", "目标会场规则；可选字符与页面检查脚本", "审稿内容可能保密；不能虚构新增实验或改动。", "说明已核验", "高"),
    c("GH-01-0013", "polish-prose", "学术语言精炼", "01", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/polish-prose/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "语言润色、术语一致、冗余、AI 痕迹", "在不改变技术主张的前提下收紧并统一学术表达。", "使用本地 lint 发现聊天残留、套话、连接词堆叠、双重缓和和术语不一致，再按会场语域逐节修改。", "科研人员、研究生、教学人员", "英文论文润色、术语统一、投稿前文字检查", "B", "保留原始数值、引文与术语锁定；脚本可直接复用。", "Python 标准库脚本", "过度润色可能改变论证强度，应进行差异复核。", "说明已核验", "高"),
    c("GH-01-0014", "research-writing-skill", "中文科研写作工作流", "01", "zLanqing/codex-claude-academic-skills", "research-writing-skill/SKILL.md", "OpenAI Codex、Anthropic Claude Code", "社区 skill、开源仓库", "中文科研写作、章节模板、润色、审稿回复", "面向中文科研用户的论文写作、修订和论证规划。", "覆盖摘要、引言、方法、结果、讨论、结论、相关工作和审稿回复，并要求保留公式、英文标题、术语、引文与测量结果。", "学生、科研人员、教学人员", "中文论文辅写、英文术语保真、学位论文和回复信", "A", "可直接使用；按学校写作规范补充模板。", "无明确外部依赖", "仍需作者提供事实、数据和引用证据。", "二级包内容验证", "高"),
    c("GH-01-0015", "paper-writing", "IMRaD 科学论文写作", "01", "beita6969/ScienceClaw", "skills/paper-writing/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "IMRaD、论文结构、引文、章节写作", "按照 IMRaD 结构辅助起草和改进科学论文。", "提供标题、摘要、引言、方法、结果、讨论和参考文献的基础写作框架，边界清晰、内容较轻量。", "学生、科研人员", "初稿结构搭建、课程论文和实验论文章节检查", "B", "移除 OpenClaw 特定路由并接入本项目引文验证规则。", "无明确外部依赖", "框架较通用，不能替代学科报告规范。", "说明已核验", "中"),
    c("GH-01-0016", "latex-writing", "学术 LaTeX 写作", "01", "beita6969/ScienceClaw", "skills/latex-writing/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "LaTeX、期刊格式、公式、表格、BibTeX", "为学术期刊和会议编写、格式化 LaTeX 文档。", "涵盖常见出版风格、公式、表格和 BibTeX，并提示不同期刊或会议格式差异。", "学生、科研人员", "论文 LaTeX 排版、复杂公式表格、期刊格式迁移", "B", "把内置示例作为起点，投稿前仍从官方模板核验。", "LaTeX 工具链", "内置模板可能过时；编译结果需检查。", "说明已核验", "中"),
    c("GH-01-0017", "peer-review", "结构化同行评审", "01", "beita6969/ScienceClaw", "skills/peer-review/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "同行评审、方法审查、统计评估、反馈", "按期刊式结构评审科学手稿并生成建设性意见。", "检查研究问题、方法、统计、清晰度和可复现性，提供主次问题与建议的统一输出模板。", "科研人员、教学人员、研究生", "组内预审、投稿前模拟评审、论文阅读训练", "B", "调整工具名称即可使用；应与统计和引文核验技能协同。", "无明确外部依赖", "评审结论只是辅助意见，不能替代领域专家。", "说明已核验", "中"),
    c("GH-01-0018", "composition-skills", "学术章节写作技能组", "01", "wentorai/research-plugins", "skills/writing/composition/SKILL.md", "其他明确命名生态（Research-Claw）", "社区 skill、开源仓库、可移植工作流", "摘要、引言、方法、讨论、章节模板", "聚合九项学术写作子技能，按章节提供模板和论证指导。", "作为导航技能连接摘要、引言、方法、讨论、综述和回复等细分指南，适合按需加载。", "学生、科研人员", "论文分章节写作、知识库按需调用", "B", "将子技能路径映射到 Codex skill 目录；优先加载所需章节。", "同仓库多个子技能", "聚合仓库规模大，需防止加载无关内容。", "说明已核验", "中"),
    c("GH-01-0019", "peer-review-assistant", "证据检索型预审助手", "01", "stephenturner/skill-peer-review-assistant", "SKILL.md", "Anthropic Claude Code / Agent Skills", "社区 skill、开源仓库", "同行评审、Consensus、背景主张、遗漏文献", "结合文献搜索检查手稿背景主张、遗漏引用和方法时效性。", "工作流先识别可检验主张，再运行定向 Consensus 搜索，区分背景证据、方法惯例和需要作者说明的问题。", "科研人员、研究生", "投稿前预审、背景引用补充、方法是否过时的检查", "C", "需将 Consensus 搜索替换为可用学术数据库或 MCP。", "Consensus 搜索服务", "依赖外部检索结果；不能将摘要匹配等同于完整证据核验。", "说明已核验", "中"),
    c("GH-01-0020", "paper-spine", "贡献主线驱动的论文构建与重写", "01", "WUBING2023/PaperSpine", "src/skill/SKILL.md", "OpenAI Codex、Anthropic Claude Code、其他明确命名生态（OpenClaw、Hermes CLI）", "社区 skill、开源仓库、跨生态可移植工作流", "论文主线、贡献确认、证据库、章节蓝图、审稿审计", "围绕已确认的核心贡献和研究动机构建、重写并审计论文或研究报告。", "提供已有稿件重写和基于材料从头构建两条主流程；先建立本地材料清单、引用支持库、贡献与动机主线，再生成章节蓝图、写作理由矩阵和正文，并通过结果验证、完整性、审稿风险、LaTeX、Word 与最终产物检查门。", "学生、科研人员、教学与科研支持人员", "论文从材料到初稿、重大结构重写、投稿前证据与审稿风险审计", "A", "Codex 入口可直接采用；高校部署宜固定提交版本，按本地工具调整外部终端配置界面，并默认停用跟随 main 的自动更新。", "Python；网络检索；按输出选择 LaTeX/PDF 或 Pandoc/Word 工具链", "流程较重且会生成较多中间产物；无固定 GitHub Release；macOS 配置界面存在公开问题；不得把 humanize 用作检测规避，也不得虚构证据或绕过付费墙。", "二级包内容验证", "高", "与 GH-01-0005 都覆盖论文编排，但本项更强调贡献—动机主线、证据支持库和可审计的硬检查门。"),

    c("GH-02-0001", "docx", "Word 文档创建与编辑", "02", "anthropics/skills", "skills/docx/SKILL.md", "Anthropic Claude Code / Agent Skills", "官方发布、开源仓库", "DOCX、Word、模板、批注、修订", "创建、读取、编辑和检查 Word 文档及模板。", "覆盖目录、标题、页码、图片、查找替换、批注、修订和渲染验证，并附带较完整的 Office 处理脚本。", "学生、教学人员、科研人员、行政人员", "报告、公文、课程材料、论文附件和模板处理", "B", "适配 Codex 的文档运行时和渲染路径；核心工作流可复用。", "Node.js/Python 与 Office 文档处理依赖", "复杂样式和修订需渲染抽查；来源技能有目录级许可证。", "二级包内容验证", "高"),
    c("GH-02-0002", "xlsx", "电子表格创建与分析", "02", "anthropics/skills", "skills/xlsx/SKILL.md", "Anthropic Claude Code / Agent Skills", "官方发布、开源仓库", "XLSX、Excel、公式、格式、图表、数据清理", "读取、创建、修复和验证电子表格文件。", "强调公式可重算、格式和图表、数据清理、冻结筛选及输出验证，附带 Office 结构处理脚本。", "学生、教学人员、科研人员、行政人员", "成绩与调查数据、预算、统计表、业务台账", "B", "接入 Codex 电子表格依赖；保留公式重算和视觉检查门。", "Python/Node.js 表格库；公式文件需重算引擎", "公式缓存和区域格式可能在不同软件间不一致。", "二级包内容验证", "高"),
    c("GH-02-0003", "pptx", "演示文稿创建与编辑", "02", "anthropics/skills", "skills/pptx/SKILL.md", "Anthropic Claude Code / Agent Skills", "官方发布、开源仓库", "PPTX、PowerPoint、模板、讲者备注、布局", "创建、读取、编辑、合并和检查 PowerPoint 文件。", "覆盖模板、布局、讲者备注、图表、批注、拆分合并与逐页渲染检查，脚本资源完整。", "学生、教学人员、科研人员、行政人员", "课堂展示、答辩、汇报、培训和会议材料", "B", "映射 Codex 的演示文稿依赖和渲染工具。", "PptxGenJS/Node.js 与渲染工具", "自动布局容易产生拥挤或遮挡，必须逐页检查。", "二级包内容验证", "高"),
    c("GH-02-0004", "pdf", "PDF 综合处理（Anthropic）", "02", "anthropics/skills", "skills/pdf/SKILL.md", "Anthropic Claude Code / Agent Skills", "官方发布、开源仓库", "PDF、提取、合并、拆分、OCR、表单", "读取、生成、转换、拆分、合并和 OCR PDF。", "提供文本表格提取、图片提取、表单、水印、旋转和加解密等常见 PDF 操作路线。", "学生、教学人员、科研人员、行政人员", "论文阅读、扫描件 OCR、材料合并与归档", "B", "使用 Codex 可用的 PDF 工具替换命令路径。", "Poppler、Python PDF/OCR 工具", "OCR 和复杂版面可能丢失结构；加密文件需合法权限。", "说明已核验", "高", "与 GH-02-0006 功能重叠但工作流和生态不同"),
    c("GH-02-0005", "doc-coauthoring", "结构化文档共创", "02", "anthropics/skills", "skills/doc-coauthoring/SKILL.md", "Anthropic Claude Code / Agent Skills", "官方发布、开源仓库、可移植工作流", "文档共创、需求澄清、迭代、读者验证", "引导用户共同撰写提案、规范、决策文档和说明材料。", "通过背景收集、结构设计、分段迭代和读者测试减少上下文遗漏，重点是写作流程而非文件格式。", "教学人员、科研人员、行政人员、学生", "项目方案、课程规范、制度草案和决策记录", "B", "把对话阶段直接转成 Codex 任务步骤；可与 docx skill 联用。", "无明确外部依赖", "需要用户持续提供上下文，不适合无人监督生成正式制度。", "说明已核验", "中"),
    c("GH-02-0006", "pdf", "PDF 创建与版式核验（OpenAI）", "02", "openai/skills", "skills/.curated/pdf/SKILL.md", "OpenAI Codex", "官方发布、开源仓库", "PDF、创建、提取、渲染、版式检查", "在 Codex 中读取、创建和审查 PDF，强调渲染核验。", "使用 ReportLab、pdfplumber、pypdf 和 Poppler 等工具，要求对版式敏感任务进行页面渲染和视觉检查。", "学生、教学人员、科研人员、行政人员", "报告导出、PDF 审阅、表格提取和页面级质量检查", "A", "可直接用于 Codex；按工作区依赖路径执行。", "Poppler 与 Python PDF 库", "文本提取不代表版式正确，仍需渲染检查。", "二级包内容验证", "高", "与 GH-02-0004 为不同官方生态实现"),
    c("GH-02-0007", "markitdown", "多格式转 Markdown", "02", "K-Dense-AI/scientific-agent-skills", "skills/markitdown/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "Markdown、Office、PDF、批量转换、RAG", "使用 Microsoft MarkItDown 将多种文档安全转换为 Markdown。", "覆盖 Office、PDF、数据文件、流、批处理、插件、视觉 OCR、Azure 提取和官方 MCP 路线。", "科研人员、学生、图书馆人员、行政人员", "资料入库、文档检索、RAG 准备和批量转换", "B", "安装对应 MarkItDown 能力或改接现有转换器。", "Microsoft MarkItDown；可选 OCR、Azure 或 MCP", "转换可能丢失复杂布局；外部 OCR 服务涉及数据边界。", "说明已核验", "高"),
    c("GH-02-0008", "scientific-slides", "科研演示文稿工作流", "02", "K-Dense-AI/scientific-agent-skills", "skills/scientific-slides/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "科研汇报、答辩、会议演讲、Beamer", "为研究报告、会议和答辩构建科学演示文稿。", "提供叙事结构、时间分配、设计模板和视觉验证，可输出 PowerPoint 或 LaTeX Beamer。", "学生、科研人员、教学人员", "组会、论文分享、学术会议、开题与答辩", "A", "可直接作为内容与视觉规则；图像生成依赖按需替换。", "PowerPoint 或 LaTeX；部分流程引用图像生成工具", "自动生成视觉素材需核验版权和科学准确性。", "说明已核验", "高"),
    c("GH-02-0009", "office-academic-skill", "中文学术 Word/PPT 工作流", "02", "zLanqing/codex-claude-academic-skills", "office-academic-skill/SKILL.md", "OpenAI Codex、Anthropic Claude Code", "社区 skill、开源仓库", "中文学术报告、论文阅读、DOCX、PPTX、讲者备注", "把论文和学位材料转换为中文 Word 报告或学术演示。", "覆盖论文阅读报告、模板匹配、可编辑 DOCX/PPTX、讲者备注、公式与英文标题保真以及版式质量门。", "学生、科研人员、教学人员", "论文汇报、组会、开题答辩、中文阅读报告", "A", "可直接用于 Codex；替换本校视觉模板即可。", "Word/PPTX 生成和渲染依赖", "必须防止公式、变量和引用在转换中被改写。", "说明已核验", "高"),
    c("GH-02-0010", "docx-manipulation", "python-docx 文档操作", "02", "claude-office-skills/skills", "docx-manipulation/SKILL.md", "Anthropic Claude Code", "社区 skill、开源仓库", "python-docx、Word、文档操作", "使用 python-docx 程序化创建和编辑 Word 文档。", "提供段落、表格、样式、图片、页眉页脚等常见操作的任务路由和代码范式。", "行政人员、教学人员、科研人员", "批量报告、公文模板、课程材料自动生成", "B", "将 Claude 特定元数据改为 Codex skill；复用 python-docx 范式。", "python-docx", "复杂 Word 特性支持有限，输出仍需版式检查。", "说明已核验", "中"),
    c("GH-02-0011", "xlsx-manipulation", "openpyxl 表格操作", "02", "claude-office-skills/skills", "xlsx-manipulation/SKILL.md", "Anthropic Claude Code", "社区 skill、开源仓库", "openpyxl、Excel、公式、样式", "使用 openpyxl 程序化创建和编辑 Excel 工作簿。", "覆盖单元格、样式、公式、图表和多表处理，适合将重复表格任务转成脚本化流程。", "行政人员、科研人员、学生", "台账、调查数据、批量工作簿和报表生成", "B", "改写工具调用并增加公式重算与渲染门。", "openpyxl", "openpyxl 不计算公式，复杂 Excel 对象可能丢失。", "说明已核验", "中"),
    c("GH-02-0012", "pptx-manipulation", "python-pptx 演示操作", "02", "claude-office-skills/skills", "pptx-manipulation/SKILL.md", "Anthropic Claude Code", "社区 skill、开源仓库", "python-pptx、PowerPoint、模板、布局", "使用 python-pptx 程序化创建和修改演示文稿。", "提供幻灯片、文本、图片、表格、图表和模板布局的操作框架，适合规则化批量任务。", "教学人员、科研人员、行政人员、学生", "批量培训课件、标准化汇报和模板填充", "B", "改写为 Codex 工具路径并增加逐页渲染检查。", "python-pptx", "不支持所有 PowerPoint 特性；自动布局需要人工复核。", "说明已核验", "中"),
    c("GH-02-0013", "md-to-office", "Markdown 转 Office", "02", "claude-office-skills/skills", "md-to-office/SKILL.md", "Anthropic Claude Code", "社区 skill、开源仓库", "Markdown、DOCX、PPTX、XLSX、转换", "把 Markdown 内容转换为常见 Office 文件。", "定义标题、列表、表格、代码块和媒体向 DOCX/PPTX 等目标格式的映射与转换路线。", "学生、教学人员、科研人员、行政人员", "笔记转报告、Markdown 方案转 Word、提纲转演示", "B", "选择本地转换工具并为目标模板增加样式映射。", "Pandoc 或 Python/Node.js Office 库", "跨格式转换可能丢失版式与语义，需要目标文件检查。", "说明已核验", "中"),
    c("GH-02-0014", "office-to-md", "Office 转 Markdown", "02", "claude-office-skills/skills", "office-to-md/SKILL.md", "Anthropic Claude Code", "社区 skill、开源仓库", "Office、Markdown、提取、知识库", "从 DOCX、XLSX、PPTX 等 Office 文件提取结构化 Markdown。", "面向后续检索、摘要和知识库处理，描述不同文件类型的文本、表格和元数据提取方式。", "图书馆人员、科研人员、行政人员、学生", "档案入库、课程材料检索、文档摘要与迁移", "B", "接入 MarkItDown 或本地 Office 解析器；保留源文件链接。", "Office 解析库或转换器", "复杂图形、批注和版式信息可能无法完整保留。", "说明已核验", "中"),
    c("GH-02-0015", "batch-convert", "多格式批量转换", "02", "claude-office-skills/skills", "batch-convert/SKILL.md", "Anthropic Claude Code", "社区 skill、开源仓库", "批量转换、格式路由、文件队列", "通过统一流程批量转换多种办公文档格式。", "提供输入扫描、格式选择、错误隔离、结果汇总和质量检查思路，适合大量材料迁移。", "行政人员、图书馆人员、教学人员", "历史材料迁移、课程文件统一格式、档案批处理", "B", "需要绑定实际转换工具；先对副本运行并保存失败清单。", "LibreOffice、Pandoc 或相应格式库", "转换可能造成样式或嵌入对象损失；仓库未附专用脚本。", "说明已核验", "中"),
    c("GH-02-0016", "officeimo-document-operator", "OfficeIMO 文档操作", "02", "EvotecIT/OfficeIMO", ".agents/plugins/officeimo-document-tools/skills/officeimo-document-operator/SKILL.md", "OpenAI Codex / Agent Skills", "社区 skill、开源仓库", "OfficeIMO、DOCX、XLSX、PPTX、PDF、邮件", "使用 OfficeIMO 检查、搜索、摘要、提取和转换本地文档。", "覆盖 Office、PDF、邮件、OneNote、OpenDocument、Markdown、HTML、CSV 和 EPUB，并提供 .NET CLI 回退路线。", "信息化人员、行政人员、图书馆人员", "本地多格式文档处理、无 COM 服务器流程", "B", "安装或提供 OfficeIMO CLI 后可用于 Codex；优先只读操作。", ".NET 8+ 与 OfficeIMO CLI/库", "格式覆盖广但特性支持不一；转换保真度需抽查。", "说明已核验", "中"),
    c("GH-02-0017", "markdown-exporter", "Markdown 多格式导出", "02", "bowenliang123/markdown-exporter", "SKILL.md", "Agent Skills / Dify", "社区 skill、开源仓库", "Markdown、DOCX、PPTX、XLSX、PDF、导出", "将 Markdown 导出为多种办公、数据和代码格式。", "支持 DOCX、PPTX、XLSX、PDF、HTML、IPYNB、CSV、JSON、XML，并可提取代码块。", "学生、教学人员、科研人员、行政人员", "一份 Markdown 多渠道发布、报告与数据文件导出", "B", "安装项目依赖并按目标格式选择导出器。", "项目 CLI/Dify 插件及各格式依赖", "多格式覆盖不代表版式一致；每种目标都需单独验收。", "说明已核验", "高"),
    c("GH-02-0018", "ai-paper2slide-skill", "论文转会议演示", "02", "Leo1998-Lu/ai-paper2slide-skill", "SKILL.md", "Agent Skills", "社区 skill、开源仓库", "论文转 PPT、学术演讲、讲者备注、图表", "把 AI 研究论文转为会议级演示文稿。", "强调论点保真、图表复用、讲述节奏、可编辑幻灯片和输出质量保证，针对科研展示而非通用 PPT。", "学生、科研人员、教学人员", "论文分享、会议报告、组会和答辩", "B", "适配 Codex 演示运行时；用本地论文和授权图片。", "PPTX 生成与 PDF/图像渲染工具", "自动提取图表需检查版权、分辨率和科学语境。", "说明已核验", "高"),
    c("GH-02-0019", "xlsx-win", "Windows 原生 Excel 自动化", "02", "dachent/skills", "xlsx-win/SKILL.md", "OpenAI Codex、Anthropic Claude Code", "社区 skill、开源仓库", "Windows、Excel COM、刷新、重算、数据透视", "在 Windows 上通过 Microsoft Excel COM 刷新、重算和验证工作簿。", "面向已有连接、缓存值、数据透视、数据模型和计算正确性，强调用真实 Excel 作为最终重算引擎。", "行政人员、科研人员、信息化人员", "复杂公式重算、现有连接刷新、Excel 环境自检", "A", "Windows 且安装桌面 Excel 时可直接使用；限制为指定工作簿。", "Windows、Microsoft 365 Excel、COM", "会操作真实 Excel 会话；宏执行和 Power Query M 编辑不在支持范围。", "说明已核验", "高"),
    c("GH-02-0020", "spreadsheet-processing", "复杂工作簿审查与编辑", "02", "kangminlee-maker/excel-workbook-editing", "SKILL.md", "Anthropic Claude Code / Agent Skills", "社区 skill、开源仓库", "工作簿审查、公式数据流、命名范围、证据包", "分析、调试、核对并验证复杂 Excel 或连接型表格。", "覆盖公式和数据流发现、跨表引用、命名范围、模板、回滚快照、Google Sheets 连接和证据/主张账本。", "行政人员、科研人员、信息化人员", "复杂台账审计、模板调试、跨表公式追踪", "B", "去除 Google Sheets 特定部分也可独立用于本地 Excel。", "Excel/Sheets 工具；视任务使用脚本", "范围很宽，执行前需限制文件和写入边界。", "说明已核验", "中"),
    c("GH-02-0021", "document-accessibility-wizard", "文档无障碍审查向导", "02", "Community-Access/accessibility-agents", "codex-skills/document-accessibility-wizard/SKILL.md", "OpenAI Codex", "社区 skill、开源仓库", "无障碍、DOCX、XLSX、PPTX、PDF、批量扫描", "引导式审查 Office 文档和 PDF 的无障碍问题。", "支持单文件、批量和递归目录，编排 Word、Excel、PowerPoint、PDF 专项检查并生成综合 Markdown 报告。", "教学人员、行政人员、学生支持人员、信息化人员", "课程材料、网站附件、行政通知和报告的无障碍审查", "B", "需要将子代理调用映射到当前 Codex 能力；规则可直接复用。", "多个专项无障碍 skill 和文档解析工具", "自动审查不能替代辅助技术用户测试；扫描目录需严格限界。", "说明已核验", "高"),
    c("GH-02-0022", "Office Remediator", "Office 无障碍修复", "02", "Community-Access/accessibility-agents", ".gemini/extensions/a11y-agents/skills/office-remediator/SKILL.md", "Gemini CLI / Agent Skills", "社区 skill、开源仓库", "无障碍修复、Word、Excel、PowerPoint", "为 Word、Excel 和 PowerPoint 生成可执行的无障碍修复方案。", "区分 python-docx、openpyxl、python-pptx 可自动修复的问题和必须在 Office UI 中手工处理的问题。", "教学人员、行政人员、信息化人员", "修复标题结构、替代文本、表格和阅读顺序问题", "B", "将 Gemini 扩展路径改造成 Codex skill，并保留人工修复清单。", "python-docx、openpyxl、python-pptx；部分 Office UI", "程序化修复覆盖有限，视觉和屏幕阅读器体验需人工验证。", "说明已核验", "高", "可与 GH-02-0021 组成审查—修复流程"),

    c("GH-03-0001", "paper-lookup", "多数据库论文检索", "03", "K-Dense-AI/scientific-agent-skills", "skills/paper-lookup/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "PubMed、PMC、arXiv、OpenAlex、Crossref、Semantic Scholar", "通过十一种学术 API 检索论文、预印本、引文和开放全文。", "按任务路由到 PubMed、Europe PMC、bioRxiv、medRxiv、arXiv、OpenAlex、Crossref、Semantic Scholar、CORE 和 Unpaywall，并保留可复现来源。", "学生、科研人员、图书馆人员", "查 DOI/PMID、找开放全文、引文网络和主题文献检索", "A", "可直接用于 Codex；按 API 可用性启用相应脚本。", "Python；多个公开学术 API", "API 覆盖和速率不同，检索结果不等同于质量判断。", "二级包内容验证", "高"),
    c("GH-03-0002", "literature-review", "系统化文献综述", "03", "K-Dense-AI/scientific-agent-skills", "skills/literature-review/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "文献综述、系统检索、研究综合、引文格式", "跨多个学术数据库开展系统化文献综述并生成报告。", "提供问题界定、数据库策略、筛选、主题综合、引用样式和 Markdown/PDF 报告模板，适用于科学与技术领域。", "学生、科研人员、图书馆人员", "综述论文、课题背景、系统检索与证据综合", "A", "直接复用流程；数据库和 PDF 生成工具按环境配置。", "学术检索 API；Python PDF 与引用工具", "完整性依赖检索策略；自动摘要不能替代全文核验。", "二级包内容验证", "高"),
    c("GH-03-0003", "research-lookup", "科研证据包检索", "03", "K-Dense-AI/scientific-agent-skills", "skills/research-lookup/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "证据包、来源提取、背景研究、竞争发现", "为科研手稿或研究简报汇集当前学术证据。", "默认路由到 Parallel Search/Extract，并把发现、全文证据和深度研究分层，适合为写作准备可追踪研究包。", "科研人员、研究生", "论文背景证据、竞争结论、研究简报", "C", "需替换 Parallel 系列工具或仅保留方法框架。", "Parallel Search/Extract/Research；可选 Perplexity", "依赖商业外部服务，未授权材料不应上传。", "说明已核验", "中"),
    c("GH-03-0004", "scholar-evaluation", "学术成果发展性评估", "03", "K-Dense-AI/scientific-agent-skills", "skills/scholar-evaluation/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "学术评价、证据追踪、量表审计、发展性反馈", "对学术作品进行证据可追踪的发展性评审。", "强调定性优先、低风险量表审计和可选本地检查，明确禁止用于人员排名和重大决策。", "教学人员、科研人员、研究生", "论文草稿反馈、课程研究作品评估、量表检查", "A", "可直接使用；将评价限定为作品改进。", "可选本地质量检查", "不适合招生、聘用或晋升等后果性决策。", "说明已核验", "中"),
    c("GH-03-0005", "open-notebook", "自托管研究笔记与文档问答", "03", "K-Dense-AI/scientific-agent-skills", "skills/open-notebook/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库、可改造工作流", "研究笔记、文档问答、向量检索、播客、自托管", "使用 Open Notebook 组织研究资料、生成笔记并跨材料检索。", "可摄取 PDF、网页、音视频和 Office 文档，支持全文与向量搜索、文档对话、摘要和多模型自托管。", "学生、科研人员、图书馆人员", "个人研究库、课题组资料问答、长文档整理", "C", "需部署 Open Notebook 并配置模型；可仅借鉴笔记组织流程。", "Docker/自托管服务、数据库和模型提供商", "部署与模型配置成本较高；导入资料需明确数据边界。", "说明已核验", "中"),
    c("GH-03-0006", "bgpt-paper-search", "全文实验数据论文检索", "03", "K-Dense-AI/scientific-agent-skills", "skills/bgpt-paper-search/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "BGPT、全文结构化数据、方法、样本量、质量分", "通过 BGPT MCP 搜索论文并提取结构化实验字段。", "返回方法、结果、样本量、质量评分和结论等二十五类以上字段，面向证据综合和实验细节查找。", "科研人员、研究生", "系统综述数据提取、实验方法和样本量比较", "C", "需要部署或连接 BGPT MCP；不可用时保留字段模板。", "BGPT MCP 服务", "外部抽取质量和覆盖需核验，不能直接作为原始研究证据。", "说明已核验", "中"),
    c("GH-03-0007", "hypothesis-generation", "可检验假设生成", "03", "K-Dense-AI/scientific-agent-skills", "skills/hypothesis-generation/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "研究问题、假设、替代解释、预测、预注册", "把观察和初步发现转化为证据有界的可检验假设。", "区分问题、候选假设、竞争解释、因果或关联主张、区分性预测、测量和预注册分析计划。", "学生、科研人员、教学人员", "研究设计课程、开题、实验计划和预注册", "A", "可直接用于 Codex；输入证据需显式标注来源。", "无明确外部依赖", "假设不是事实，生成内容可能受输入偏差影响。", "说明已核验", "高"),
    c("GH-03-0008", "scientific-critical-thinking", "科学证据批判性分析", "03", "K-Dense-AI/scientific-agent-skills", "skills/scientific-critical-thinking/SKILL.md", "Agent Skills（兼容 Codex）", "社区 skill、开源仓库", "研究设计、偏倚、混杂、GRADE、风险评估", "评估科学主张、研究设计和证据质量。", "识别偏倚、混杂和无效推断，介绍 GRADE、Cochrane 风险工具等框架，适合教学与研究阅读。", "学生、教学人员、科研人员", "论文研读、研究方法教学、证据质量检查", "A", "可直接使用；按学科替换评价框架。", "无明确外部依赖", "框架性判断仍需领域知识和完整材料。", "说明已核验", "高"),
    c("GH-03-0009", "academic-literature-search", "中文学术检索与引用管理", "03", "beita6969/ScienceClaw", "skills/academic-literature-search/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "PubMed、中文流程、工具路由、引文管理", "以中文说明多工具学术检索和引文管理流程。", "提供平台选择矩阵、PubMed MCP 操作、检索策略、结果组织和引用处理，适合中文科研工作流。", "学生、科研人员、图书馆人员", "中文课题检索培训、医学与综合文献检索", "C", "替换 OpenClaw MCP 名称并保留平台路由表。", "PubMed MCP 及其他外部搜索工具", "工具依赖较强，部分数据库范围偏医学。", "说明已核验", "中"),
    c("GH-03-0010", "arxiv-search", "arXiv 预印本检索", "03", "beita6969/ScienceClaw", "skills/arxiv-search/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "arXiv、预印本、作者、分类、元数据", "按主题、作者和分类检索 arXiv 预印本。", "解释 arXiv API 查询语法、学科代码和元数据字段，并区分预印本与正式期刊检索。", "学生、科研人员", "计算机、物理、数学等领域前沿预印本跟踪", "B", "映射到 Codex 网络或本地 API 脚本。", "arXiv API", "预印本未必经过同行评审；API 速率需遵守。", "说明已核验", "中"),
    c("GH-03-0011", "biorxiv-search", "bioRxiv 语义检索", "03", "beita6969/ScienceClaw", "skills/biorxiv-search/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "bioRxiv、生命科学、预印本、语义检索", "用自然语言语义检索 bioRxiv 生命科学预印本。", "通过 Valyu 驱动的脚本返回与自然语言查询相关的 bioRxiv 结果，适合发现关键词难以覆盖的研究。", "科研人员、研究生", "生命科学前沿追踪、预印本发现", "C", "需要配置 Valyu；也可改为 bioRxiv 官方 API 关键词检索。", "Valyu 服务与仓库脚本", "商业语义搜索的排序和覆盖不可完全复现。", "说明已核验", "中"),
    c("GH-03-0012", "crossref-search", "Crossref DOI 与出版元数据", "03", "beita6969/ScienceClaw", "skills/crossref-search/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "Crossref、DOI、期刊元数据、出版社", "通过 Crossref API 查询 DOI、出版物和期刊元数据。", "支持 DOI 解析、作品搜索和出版者信息，明确不用于全文下载。", "科研人员、学生、图书馆人员", "参考文献校验、DOI 补全、出版元数据核对", "B", "替换为 Codex HTTP 或现有 paper-lookup 脚本。", "Crossref REST API", "元数据由成员提交，字段可能缺失或存在版本差异。", "说明已核验", "中"),
    c("GH-03-0013", "dblp-search", "DBLP 计算机文献检索", "03", "beita6969/ScienceClaw", "skills/dblp-search/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "DBLP、计算机科学、作者、会议、期刊", "通过 DBLP API 查询计算机科学出版物、作者和会场。", "适合作者成果列表、会议论文集和 CS 书目信息，明确不提供跨学科覆盖和完整引文数。", "计算机类学生、科研人员、图书馆人员", "CS 文献检索、作者消歧、会议论文集核对", "B", "映射到 Codex HTTP 请求或 find-papers 脚本。", "DBLP API", "作者同名和会场别名需要进一步处理。", "说明已核验", "中"),
    c("GH-03-0014", "openalex-search", "OpenAlex 开放学术图谱检索", "03", "beita6969/ScienceClaw", "skills/openalex-search/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "OpenAlex、作者、机构、概念、开放引文", "通过 OpenAlex 查询论文、作者、机构和开放引文数据。", "提供实体检索、过滤和概念映射，适合机构分析、作者概况和开放书目研究。", "科研人员、图书馆人员、科研管理人员", "机构科研分析、作者画像、主题与引文网络", "B", "映射到 paper-lookup 或直接 OpenAlex API。", "OpenAlex API", "实体消歧和概念标签并非人工权威分类。", "说明已核验", "高"),
    c("GH-03-0015", "semantic-scholar", "Semantic Scholar 引文图谱", "03", "beita6969/ScienceClaw", "skills/semantic-scholar/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "Semantic Scholar、引文图、作者、推荐、文献计量", "跨学科检索 Semantic Scholar 并遍历引用和参考文献。", "涵盖论文、作者、推荐和批量接口，适合引用链追踪和文献计量初筛。", "学生、科研人员、图书馆人员", "种子论文扩展、相关论文推荐、引文网络", "B", "映射到 paper-lookup 或 Semantic Scholar API。", "Semantic Scholar API；高频请求可能需要密钥", "引用数和论文合并记录会更新，不能作为唯一评价依据。", "说明已核验", "高"),
    c("GH-03-0016", "lit-synthesizer", "文献搜索与引用图综合", "03", "beita6969/ScienceClaw", "skills/lit-synthesizer/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "PubMed、bioRxiv、摘要、引用图、综述段落", "搜索 PubMed 和 bioRxiv，生成摘要、引用图和综述段落。", "把检索、LLM 摘要、引用图构建和写作串成一条紧凑流水线。", "科研人员、研究生", "快速主题扫描、综述草稿和引用关系探索", "C", "需要确认仓库列出的脚本和模型依赖；可拆分成独立阶段。", "Python、学术 API、LLM", "端到端自动化容易把摘要错误传播到综述文本。", "说明已核验", "中"),
    c("GH-03-0017", "meta-analysis", "定量 Meta 分析", "03", "beita6969/ScienceClaw", "skills/meta-analysis/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "效应量、森林图、漏斗图、异质性、发表偏倚", "合并多项研究并进行定量 Meta 分析。", "覆盖常用效应量、固定/随机效应、异质性、森林图、漏斗图和发表偏倚检查。", "科研人员、研究生", "系统综述定量综合、教学演示和分析计划", "B", "将统计实现映射到 statsmodels/R 等可验证工具并保存数据表。", "统计计算库和结构化研究数据", "模型选择和研究可比性必须由研究者判断。", "说明已核验", "高"),
    c("GH-03-0018", "asreview-screening", "ASReview 文献筛选", "03", "beita6969/ScienceClaw", "skills/asreview-screening/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "系统综述、主动学习、题录筛选、纳排", "使用 ASReview 主动学习为系统综述优先排序题录。", "适合大规模纳入排除筛选，降低人工阅读负担，并明确它不负责文献搜索或 Meta 分析。", "科研人员、研究生、图书馆人员", "系统综述标题摘要筛选、优先阅读排序", "C", "安装 ASReview 后使用；保留人工纳排标准和双人复核。", "ASReview、题录数据集", "主动学习可能漏掉少数类型研究，停止规则需预先定义。", "说明已核验", "中"),
    c("GH-03-0019", "academic-deep-research", "可复现深度学术调研", "03", "beita6969/ScienceClaw", "skills/academic-deep-research/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库、可移植工作流", "深度调研、双循环检索、证据层级、用户检查点", "以公开方法和多轮检索开展深度研究。", "要求每个主题至少两轮研究、APA 引用、证据层级和三个用户检查点，强调不是黑箱 API 包装。", "科研人员、学生、行政研究人员", "背景调研、政策简报、复杂主题综述", "C", "将 OpenClaw 原生工具替换为 Codex 搜索与读取工具。", "web_search、web_fetch、会话并行工具", "范围较宽，若问题界定不清会产生大量低价值材料。", "说明已核验", "中"),
    c("GH-03-0020", "paper-analysis", "科学论文阅读与批判分析", "03", "beita6969/ScienceClaw", "skills/paper-analysis/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "论文阅读、摘要、方法、局限、贡献", "读取、摘要并批判性分析科学论文。", "从论文获取开始，按研究问题、方法、结果、局限、贡献和可信度生成不同深度的阅读报告。", "学生、教学人员、科研人员", "课程阅读、组会准备、方法比较和数据提取", "B", "替换论文获取工具；保留快速与深度两级输出。", "PDF/URL/DOI 获取工具", "仅凭摘要不能完成方法和局限分析。", "说明已核验", "高"),
    c("GH-03-0021", "systematic-review", "PRISMA 系统综述编排", "03", "beita6969/ScienceClaw", "skills/systematic-review/SKILL.md", "其他明确命名生态（OpenClaw）", "社区 skill、开源仓库", "PRISMA、协议、检索、筛选、提取、证据综合", "按 PRISMA 2020 编排系统综述与 Meta 分析流程。", "从协议、数据库搜索、筛选、数据提取到证据综合提供阶段化工作流，并区分叙述性综述。", "科研人员、研究生、图书馆人员", "系统综述、范围综述、证据综合项目管理", "B", "将子技能和工具路由映射到本知识库候选。", "多个检索、筛选、提取和统计子技能", "PRISMA 报告合规不等于方法质量；协议应预先确定。", "说明已核验", "高"),
    c("GH-03-0022", "academic-search", "多平台学术检索框架", "03", "ustc-ai4science/academic-search", "SKILL.md", "OpenAI Codex、Anthropic Claude Code", "社区 skill、开源仓库", "学术检索、平台选择、检索策略、中文指南", "以平台选择矩阵和分层策略组织学术搜索。", "仓库包含 OpenAI agent 配置、检索框架图、参考资料和脚本，强调先做前置检查，再按问题类型选数据库和查询式。", "学生、科研人员、图书馆人员", "跨学科文献查找、检索策略教学和复杂查询规划", "A", "可直接使用；按学校订购数据库补充入口。", "网络检索；仓库包含可选脚本和参考资源", "不同平台访问权限不同，搜索结果需保留来源。", "二级包内容验证", "高"),
    c("GH-03-0023", "litdb", "本地文献与文档数据库", "03", "jkitchin/litdb", "SKILL.md", "生态中立 / MCP", "社区 skill、开源仓库", "文献数据库、文档索引、MCP、全文检索、研究资料", "使用 litdb 建立并查询本地科研文献与文档数据库。", "提供文献摄取、搜索、文档关联和 MCP 接口，仓库包含测试、构建和详细使用资料。", "科研人员、研究生、图书馆人员", "个人或课题组文献库、本地全文检索和研究记录", "C", "部署 litdb 与 MCP 后接入；也可借鉴其数据模型。", "litdb 软件、数据库和 MCP 服务", "需要维护本地索引与附件；导入版权受限全文时需遵守许可。", "二级包内容验证", "中"),
    c("GH-03-0024", "find-papers", "免密钥多源论文检索", "03", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/find-papers/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "DBLP、Crossref、Semantic Scholar、arXiv、会场别名", "无需 API 密钥跨四个来源搜索论文、作者、会场和引文。", "附带缓存、限流友好脚本和会场别名表，可查论文集、DOI、引用数与近期预印本。", "学生、科研人员、图书馆人员", "CS 与跨学科检索、会议论文集、种子论文扩展", "B", "引入仓库脚本并按 Codex 路径调整。", "Python 标准库脚本；公开学术 API", "公共 API 可能限流，引用数跨平台不可直接比较。", "二级包内容验证", "高"),
    c("GH-03-0025", "fetch-paper", "合法开放全文获取", "03", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/fetch-paper/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "开放获取、全文、PDF、合法来源", "为已识别论文寻找并获取合法开放全文。", "按 DOI、预印本和开放仓储路线定位全文，并为后续阅读与综述提供本地材料。", "学生、科研人员、图书馆人员", "获取可读全文、综述语料准备、论文阅读", "B", "映射到 Unpaywall、PMC、arXiv 等允许来源。", "公开全文服务；可选 PDF 工具", "不能绕过付费墙或许可；下载版本需与引用版本对应。", "说明已核验", "高"),
    c("GH-03-0026", "literature-review", "可核验引文的主题综述", "03", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/literature-review/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "主题综述、筛选语料、主张锚点、引用门", "构建每个主张都绑定已核验来源的结构化文献综述。", "组合 find-papers、fetch-paper 和 verify-citations，跟踪筛选语料、章节级主张锚点和最终确定性检查。", "科研人员、研究生", "论文综述章节、主题研究、相关工作全景", "B", "需要同仓库检索与引用验证技能协同。", "多个兄弟 skill 与本地检查脚本", "综述范围和纳排标准仍需研究者预先确定。", "说明已核验", "高", "与 GH-03-0002 是不同工作流实现"),
    c("GH-03-0027", "draft-survey", "阅读清单与综述论文草稿", "03", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/draft-survey/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "阅读清单、论文排序、主题分类、综述草稿", "把主题转为排序阅读清单和双栏综述草稿。", "按影响、会场、时效和引文图中心性排序论文，形成分类体系、开放问题和带验证引用的原创综合。", "科研人员、研究生", "快速进入新领域、课程阅读清单、综述论文初稿", "B", "复用搜索与引文核验兄弟 skill；排名指标按学科调整。", "find-papers、verify-citations、LaTeX", "引用量排序可能偏向老论文，不能替代内容相关性判断。", "说明已核验", "高"),
    c("GH-03-0028", "verify-claims", "论文关键主张核验", "03", "ShaishavMaisuria/research-paper-lifecycle-skills", "skills/verify-claims/SKILL.md", "Agent Skills", "社区 skill、开源仓库", "主张审计、结果、表格、图形、过度推断", "把论文中的关键主张与结果、表格、图形和引文逐项核对。", "检查首创性、SOTA、显著性措辞、数字不一致和 rebuttal/终稿中的证据支持关系。", "科研人员、研究生、教学人员", "投稿前主张审计、结果一致性和过度推断检查", "B", "接入本地稿件和证据清单即可；避免上传敏感材料。", "稿件、结果表、图形和引用证据", "核验质量取决于能否访问完整实验记录。", "说明已核验", "高"),
    c("GH-03-0029", "Search SOP", "文献检索标准操作规程", "03", "wentorai/Research-Claw", "skills/search-sop/SKILL.md", "其他明确命名生态（Research-Claw）", "社区 skill、开源仓库、可移植工作流", "三层检索、参考管理器、数据库、网络搜索", "以标准操作规程组织分层文献搜索。", "从本地参考管理器导入开始，再进入专业数据库和补充搜索，强调查询记录、去重与可复现性。", "科研人员、学生、图书馆人员", "课题组统一检索规范、综述检索培训", "C", "把 Research-Claw 工具名替换为现有搜索和文献管理工具。", "本地参考管理器、数据库和网络搜索", "仓库许可证未明确；工具路线较多需按任务裁剪。", "说明已核验", "中"),
    c("GH-03-0030", "Survey SOP", "综述深读与综合规程", "03", "wentorai/Research-Claw", "skills/survey-sop/SKILL.md", "其他明确命名生态（Research-Claw）", "社区 skill、开源仓库、可移植工作流", "综述、深度阅读、阅读分级、综合", "规范主题综述中的范围、深读、证据提取和综合步骤。", "提供阅读深度等级和阶段式工作流，帮助把广泛筛选与关键论文精读分开。", "科研人员、研究生", "综述写作、读书会、研究领域进入", "C", "保留方法框架，替换 Research-Claw 调度与存储路径。", "Research-Claw 工作流", "仓库许可证未明确；需要与具体检索和引用工具配套。", "说明已核验", "中"),
    c("GH-03-0031", "slr-prisma", "PRISMA 2020 系统综述向导", "03", "keemanxp/slr-prisma", "SKILL.md", "Anthropic Claude Code / Agent Skills", "社区 skill、开源仓库", "PRISMA 2020、系统综述、纳排、流程图、APA", "按 PRISMA 2020 引导用户完成系统文献综述。", "覆盖二十七项清单、访谈式范围确定、数据库策略、纳排标准、偏倚评估、叙述综合、Word 手稿和带注释流程图；不做统计合并。", "科研人员、研究生、教学人员", "系统综述课程、毕业论文、PRISMA 报告审计", "B", "替换 Claude 专用工具路径，并与本地 docx 生成技能协同。", "Word/图表生成工具；用户提供筛选数据", "仓库许可证未明确；PRISMA 合规不等于检索全面。", "说明已核验", "高"),
]


# 第二轮：图书馆与信息素养；编程、数学、数据分析和可视化。
# 该模块从只读 GitHub 核验记录生成规范条目，并更新重复仓库的当日元数据。
from catalog_data_round2 import (  # noqa: E402
    ROUND2_CANDIDATES,
    ROUND2_CATEGORIES,
    ROUND2_REPOSITORIES,
)

CATEGORIES.update(ROUND2_CATEGORIES)
REPOSITORIES.update(ROUND2_REPOSITORIES)
CANDIDATES.extend(ROUND2_CANDIDATES)
