#!/usr/bin/env python3
"""Finalize or check an econ-review v0.4 package as one fail-closed transaction."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
from safe_io import (  # noqa: E402
    atomic_write_bytes,
    atomic_write_json,
    atomic_write_text,
    canonical_portable_path,
    is_link_or_junction,
    safe_read_bytes,
    sha256_bytes,
    strict_json_load,
)
from trust_spine import pdf_sources, validate_pdf_ingestions  # noqa: E402
from validate_review import validate_review  # noqa: E402
from review_timing import STATE_NAME as TIMING_STATE_NAME, finish_delivery_for_finalizer  # noqa: E402


SCRIPT_DIR = Path(__file__).resolve().parent
GENERATORS = (
    SCRIPT_DIR / "generate_verification.py",
    SCRIPT_DIR / "generate_sources.py",
    SCRIPT_DIR / "generate_coverage.py",
    SCRIPT_DIR / "round_reconciliation.py",
    SCRIPT_DIR / "generate_reports.py",
    SCRIPT_DIR / "generate_fix_plan.py",
    SCRIPT_DIR / "generate_pdf_report.py",
)
REPORT_RENDERERS = ("auto", "reportlab", "latexmk-lualatex", "lualatex", "tectonic")


def copy_or_link(source: str, destination: str) -> str:
    """Hard-link immutable staging inputs when possible, with a Windows-safe copy fallback.

    Every generated artifact is replaced atomically inside the staging tree, so
    linking the initial bytes cannot mutate the canonical package.
    """

    try:
        os.link(source, destination)
    except OSError:
        return shutil.copy2(source, destination)
    return destination


def load_object(path: Path) -> dict[str, Any]:
    value = strict_json_load(path)
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain an object")
    return value


def reject_symlinks(root: Path) -> None:
    if is_link_or_junction(root) or not root.is_dir():
        raise ValueError("review directory must be a real directory")
    for directory, names, files in os.walk(root, followlinks=False):
        base = Path(directory)
        for name in names + files:
            path = base / name
            if is_link_or_junction(path):
                raise ValueError(
                    f"review packages may not contain links or junctions: {path.relative_to(root)}"
                )


def run_generators(review_dir: Path, *, check: bool, renderer: str = "auto") -> None:
    run = load_object(review_dir / "run.json")
    for script in GENERATORS:
        if script.name == "generate_coverage.py" and run.get("mode") != "full":
            continue
        if script.name == "round_reconciliation.py":
            if run.get("prior_round") is None:
                continue
            command = [sys.executable, str(script), str(review_dir)]
            if not check:
                command.append("--write")
        else:
            command = [sys.executable, str(script), str(review_dir)]
            if script.name == "generate_pdf_report.py":
                command.extend(["--renderer", renderer])
            if check:
                command.append("--check")
        result = subprocess.run(
            command,
            capture_output=True,
            encoding="utf-8",
            errors="replace",
        )
        if result.returncode:
            detail = result.stderr.strip() or result.stdout.strip()
            raise ValueError(f"{script.name} failed: {detail}")


def artifact_hashes(review_dir: Path) -> dict[str, str]:
    excluded_root = {"finalization.json", "review-actions.json"}
    artifacts: dict[str, str] = {}
    folded_paths: dict[str, str] = {}
    for path in sorted(review_dir.rglob("*")):
        if not path.is_file() or path.name == ".DS_Store":
            continue
        relative = canonical_portable_path(path.relative_to(review_dir).as_posix())
        if relative in excluded_root:
            continue
        folded = relative.casefold()
        if folded in folded_paths:
            raise ValueError(
                "review package contains case-ambiguous artifact paths: "
                f"{folded_paths[folded]}, {relative}"
            )
        folded_paths[folded] = relative
        artifacts[relative] = sha256_bytes(safe_read_bytes(review_dir, relative))
    return artifacts


def uses_current_generators(review_dir: Path, run: dict[str, Any]) -> bool:
    """Return whether the installed deterministic renderers created a receipt.

    Immutable v0.4 receipt-v0.1 packages and full receipt-v0.2 packages retain
    their original generated bytes. Their receipt hashes remain verifiable,
    but replaying a newer renderer would incorrectly demand a migration.
    """
    path = review_dir / "finalization.json"
    if not path.exists():
        return True
    try:
        value = load_object(path)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError):
        return True
    version = value.get("schema_version")
    if version == "0.1":
        return False
    if version in {"0.2", "0.3"}:
        artifacts = value.get("artifacts")
        if isinstance(artifacts, dict) and "paper-review.pdf" not in artifacts:
            # Receipt-v0.2/v0.3 packages finalized before PDF delivery retain their
            # original generated bytes and remain verifiable without migration.
            return False
    if version == "0.2" and run.get("mode") == "full":
        return False
    return True


def receipt(review_dir: Path, run: dict[str, Any]) -> dict[str, Any]:
    gates = [
        "source_integrity",
        "structured_verification",
        "report_generation",
        "fix_plan_generation",
        "contract_validation",
    ]
    if run.get("mode") == "full":
        gates[2:2] = ["structured_audit_v02", "burden_coverage_v02"]
    source_manifest = load_object(review_dir / "evidence" / "source-manifest.json")
    if pdf_sources(source_manifest):
        gates.insert(1, "source_ingestion")
    selected_renderer = selected_report_renderer(review_dir)
    return {
        # Receipt v0.3 specifically certifies the full-review burden-coverage
        # guarantee. Quick reviews retain v0.2 because they do not carry that
        # artifact or gate.
        "schema_version": "0.3" if run.get("mode") == "full" else "0.2",
        "review_id": run["review_id"],
        "contract_version": "0.4",
        "report_renderer": selected_renderer,
        "artifacts": artifact_hashes(review_dir),
        "gates": gates,
    }


def selected_report_renderer(review_dir: Path) -> str:
    """Read the renderer actually selected for the canonical report PDF."""

    profile_path = review_dir / "evidence" / "pdf-render-profile.json"
    if profile_path.is_file():
        profile = load_object(profile_path)
        selected_renderer = profile.get("renderer")
        if selected_renderer not in REPORT_RENDERERS[2:]:
            raise ValueError("PDF render profile names an unsupported renderer")
        return str(selected_renderer)
    return "reportlab"


def synchronize_renderer_provenance(review_dir: Path) -> dict[str, Any]:
    """Persist the selected backend in run provenance before receipt hashing."""

    run = load_object(review_dir / "run.json")
    provenance = run.get("provenance")
    if not isinstance(provenance, dict):
        raise ValueError("run.json.provenance must be an object before finalization")
    provenance["renderer"] = selected_report_renderer(review_dir)
    atomic_write_json(review_dir, "run.json", run)
    return run


def recorded_renderer(review_dir: Path) -> str | None:
    """Return a finalized package's renderer for deterministic auto replay."""

    finalization_path = review_dir / "finalization.json"
    if not finalization_path.is_file():
        return None
    try:
        renderer = load_object(finalization_path).get("report_renderer")
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError):
        return None
    return str(renderer) if renderer in REPORT_RENDERERS[1:] else None


def readiness_errors(review_dir: Path, run: dict[str, Any], ledger: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if run.get("schema_version") != "0.4" or ledger.get("schema_version") != "0.4":
        errors.append("finalization requires matching v0.4 run and findings contracts")
    if run.get("schema_version") == "0.4":
        raw_title = run.get("paper_title")
        title = raw_title.strip() if isinstance(raw_title, str) else ""
        words = re.findall(r"[^\W\d_][^\s]*", title, flags=re.UNICODE)
        letters = re.findall(r"[^\W\d_]", title, flags=re.UNICODE)
        equation_marks = sum(title.count(mark) for mark in "=<>∑∫√±×÷{}[]_")
        generic = title.casefold() in {
            "untitled manuscript", "manuscript", "paper", "source",
            "original", "referee report", "paper review",
        }
        extraction_artifact = (
            title.startswith(("#", "$", "\\[", "\\("))
            or "<!--" in title
            or "pdf page" in title.casefold()
        )
        if (
            not 8 <= len(title) <= 240
            or generic
            or extraction_artifact
            or len(letters) < 6
            or len(words) < 2
            or equation_marks > max(2, len(words) // 2)
        ):
            errors.append(
                "v0.4 finalization requires a clean run.json.paper_title; "
                "verify it from the manuscript title page"
            )
    if run.get("schema_version") == "0.4" and run.get("mode") == "full":
        comment_policy = run.get("comment_policy")
        if not isinstance(comment_policy, dict):
            errors.append("v0.4 full finalization requires run.json.comment_policy")
        else:
            if comment_policy.get("maximum") is not None:
                errors.append(
                    "v0.4 full finalization requires the legacy comment_policy.maximum to be null"
                )
            if comment_policy.get("substance_maximum") != 100:
                errors.append(
                    "v0.4 full finalization requires comment_policy.substance_maximum 100"
                )
            if comment_policy.get("writing_maximum") != 30:
                errors.append(
                    "v0.4 full finalization requires comment_policy.writing_maximum 30"
                )
        required_component_versions = {
            "evidence/candidates.json": "0.1",
            "evidence/claims.json": "0.2",
            "evidence/analytical-audit.json": "0.2",
            "evidence/external-sources.json": "0.4",
            "evidence/coverage.json": "0.2",
            "evidence/writing.json": "0.4",
        }
        for relative, required_version in required_component_versions.items():
            try:
                component = load_object(review_dir / relative)
            except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
                errors.append(f"cannot validate {relative} contract: {exc}")
                continue
            if component.get("schema_version") != required_version:
                errors.append(
                    f"v0.4 full finalization requires {relative} schema_version {required_version}"
                )
        requested_addons = run.get("requested_addons")
        if not isinstance(requested_addons, list):
            errors.append(
                "v0.4 full finalization requires run.json.requested_addons (use [] when none were requested)"
            )
        try:
            figures = load_object(review_dir / "evidence/figures.json")
        except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
            errors.append(f"cannot validate evidence/figures.json contract: {exc}")
        else:
            if figures.get("figures") and figures.get("schema_version") != "0.2":
                errors.append(
                    "v0.4 full finalization with figures requires evidence/figures.json schema_version 0.2"
                )
        try:
            tables = load_object(review_dir / "evidence/tables.json")
        except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
            errors.append(f"cannot validate evidence/tables.json contract: {exc}")
        else:
            if tables.get("tables") and tables.get("schema_version") != "0.2":
                errors.append(
                    "v0.4 full finalization with tables requires evidence/tables.json schema_version 0.2"
                )
    if run.get("verification_passed") is not True:
        errors.append("run.json.verification_passed must be true before finalization")
    stages = run.get("stage_status", {})
    if not isinstance(stages, dict) or any(value not in {"passed", "bounded", "not_applicable"} for value in stages.values()):
        errors.append("all workflow stages must be passed, bounded, or not applicable")
    for finding in ledger.get("findings", []):
        if not isinstance(finding, dict) or finding.get("status") in {"dismissed", "resolved"}:
            continue
        if finding.get("severity") in {"critical", "major", "minor", "info"} and finding.get("verification") != "passed":
            errors.append(f"finding {finding.get('id')} has not passed verification")
    try:
        source_manifest = load_object(review_dir / "evidence" / "source-manifest.json")
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        errors.append(f"cannot validate source ingestion readiness: {exc}")
    else:
        errors.extend(
            validate_pdf_ingestions(
                review_dir,
                source_manifest,
                run.get("review_id"),
                require_ready=True,
                require_canonical_paths=True,
            )
        )
    return errors


def check(review_dir: Path, *, renderer: str = "auto") -> list[str]:
    try:
        reject_symlinks(review_dir)
        run = load_object(review_dir / "run.json")
        if uses_current_generators(review_dir, run):
            if renderer == "auto":
                renderer = recorded_renderer(review_dir) or renderer
            run_generators(review_dir, check=True, renderer=renderer)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        return [str(exc)]
    return validate_review(review_dir)


def completion_preflight(review_dir: Path) -> list[str]:
    """Run completion semantics before mutating status or generating reports.

    Drift in a deterministic Markdown projection is generator-resolvable and is
    checked independently after generation. Structured/schema/completion errors
    are never filtered here.
    """

    try:
        reject_symlinks(review_dir)
        run = load_object(review_dir / "run.json")
        ledger = load_object(review_dir / "findings.json")
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        return [str(exc)]
    combined = readiness_errors(review_dir, run, ledger)
    combined.extend(
        error
        for error in validate_review(review_dir, strict_complete=True)
        if " is not synchronized" not in error
    )
    return list(dict.fromkeys(combined))


def finalize(review_dir: Path, *, renderer: str = "auto") -> None:
    review_dir = review_dir.expanduser().absolute()
    reject_symlinks(review_dir)
    review_dir = review_dir.resolve(strict=True)
    run = load_object(review_dir / "run.json")
    if errors := completion_preflight(review_dir):
        raise ValueError("completion preflight failed:\n- " + "\n- ".join(errors))
    with tempfile.TemporaryDirectory(prefix="econ-review-finalize-") as temporary:
        staged = Path(temporary) / "review"
        shutil.copytree(review_dir, staged, copy_function=copy_or_link)
        staged_run = load_object(staged / "run.json")
        staged_run["status"] = "complete"
        atomic_write_json(staged, "run.json", staged_run)
        finalization_path = staged / "finalization.json"
        if finalization_path.exists():
            finalization_path.unlink()
        run_generators(staged, check=False, renderer=renderer)
        run_generators(staged, check=True, renderer=renderer)
        staged_run = synchronize_renderer_provenance(staged)
        timing_completed = finish_delivery_for_finalizer(staged)
        if timing_completed:
            staged_run = load_object(staged / "run.json")
        atomic_write_json(staged, "finalization.json", receipt(staged, staged_run))
        errors = validate_review(staged)
        if errors:
            raise ValueError("staged package failed validation:\n- " + "\n- ".join(errors))

        # The receipt is the commit marker and is deliberately written last.
        text_commit_paths = [
            "run.json", "review-manifest.json", "README.md", "report.md", "fix-plan.md",
            "evidence/verification.md", "evidence/sources.md",
        ]
        if staged_run.get("mode") == "full":
            text_commit_paths.append("evidence/coverage.md")
        if staged_run.get("prior_round") is not None:
            text_commit_paths.append("evidence/round-reconciliation.md")
        if (staged / "editing-comments.md").exists():
            text_commit_paths.append("editing-comments.md")
        profile_relative = "evidence/pdf-render-profile.json"
        binary_commit_paths = ["paper-review.pdf"]
        if (staged / profile_relative).exists():
            binary_commit_paths.append(profile_relative)
        rollback_paths = list(dict.fromkeys(
            text_commit_paths
            + binary_commit_paths
            + [profile_relative, "finalization.json", TIMING_STATE_NAME]
        ))
        previous = {
            relative: safe_read_bytes(review_dir, relative)
            for relative in rollback_paths
            if (review_dir / relative).exists()
        }
        try:
            for relative in text_commit_paths:
                atomic_write_text(review_dir, relative, (staged / relative).read_text(encoding="utf-8"))
            for relative in binary_commit_paths:
                atomic_write_bytes(review_dir, relative, safe_read_bytes(staged, relative))
            if profile_relative not in binary_commit_paths:
                stale_profile = review_dir / profile_relative
                if stale_profile.exists() and not stale_profile.is_symlink():
                    stale_profile.unlink()
            timing_state = review_dir / TIMING_STATE_NAME
            if timing_completed and timing_state.exists():
                timing_state.unlink()
            atomic_write_json(review_dir, "finalization.json", load_object(staged / "finalization.json"))
            # The staged package already passed a full independent generator
            # replay. After committing those exact bytes, revalidate hashes,
            # source bindings, semantics, and receipt closure without compiling
            # the PDF a third time.
            errors = validate_review(review_dir)
            if errors:
                raise ValueError("committed package failed final check:\n- " + "\n- ".join(errors))
        except Exception as exc:
            try:
                for relative in rollback_paths:
                    if relative in previous:
                        atomic_write_bytes(review_dir, relative, previous[relative])
                    else:
                        path = review_dir / relative
                        if path.exists() and not path.is_symlink():
                            path.unlink()
            except Exception as rollback_exc:
                raise ValueError(f"{exc}; rollback failed: {rollback_exc}") from rollback_exc
            raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("review_dir", type=Path)
    parser.add_argument("--check", action="store_true", help="Check an existing finalized package without writing")
    parser.add_argument(
        "--preflight",
        action="store_true",
        help="Apply strict completion checks without changing status or generating reports",
    )
    parser.add_argument(
        "--renderer",
        choices=REPORT_RENDERERS,
        default="auto",
        help=(
            "Report backend for finalization (default: health-checked TeX, then ReportLab); "
            "use reportlab for an explicit portable override"
        ),
    )
    parser.add_argument(
        "--delivery-dir",
        type=Path,
        help=(
            "Create a clean reader delivery directory after finalization. "
            "When review_dir is named supporting, its parent is used automatically."
        ),
    )
    args = parser.parse_args()
    try:
        if args.check and args.preflight:
            raise ValueError("--check and --preflight are mutually exclusive")
        if args.check:
            if args.delivery_dir is not None:
                raise ValueError("--delivery-dir cannot be combined with --check")
            errors = check(args.review_dir.expanduser().absolute(), renderer=args.renderer)
            if errors:
                raise ValueError("\n- ".join(errors))
        elif args.preflight:
            if args.delivery_dir is not None:
                raise ValueError("--delivery-dir cannot be combined with --preflight")
            errors = completion_preflight(args.review_dir.expanduser().absolute())
            if errors:
                raise ValueError("\n- ".join(errors))
        else:
            finalize(args.review_dir, renderer=args.renderer)
            delivery_dir = args.delivery_dir
            if delivery_dir is None and args.review_dir.name == "supporting":
                delivery_dir = args.review_dir.parent
            if delivery_dir is not None:
                from create_delivery import create_delivery

                create_delivery(
                    args.review_dir,
                    delivery_dir,
                    replace=True,
                    prevalidated=True,
                )
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as exc:
        parser.exit(1, f"finalization failed: {exc}\n")
    action = "completion preflight" if args.preflight else "finalization"
    print(f"econ-review {action} passed: {args.review_dir}")
    return 0


if __name__ == "__main__":
    from cli_io import configure_utf8_stdio

    configure_utf8_stdio()
    raise SystemExit(main())
